Repository doctrine/DoctrineMigrationsBundle, pull requests merged in 2019-11, with the labels that each got.

#282 Update supported PHP version
  .travis.yml
  Command/Helper/DoctrineCommandHelper.php
  Command/MigrationsDiffDoctrineCommand.php
  Command/MigrationsDumpSchemaDoctrineCommand.php
  Command/MigrationsExecuteDoctrineCommand.php
  Command/MigrationsGenerateDoctrineCommand.php
  Command/MigrationsLatestDoctrineCommand.php
  Command/MigrationsMigrateDoctrineCommand.php
  Command/MigrationsRollupDoctrineCommand.php
  Command/MigrationsStatusDoctrineCommand.php
  Command/MigrationsUpToDateDoctrineCommand.php
  Command/MigrationsVersionDoctrineCommand.php
  composer.json
  composer.lock
Labels: Improvement

#275 Lazy console commands
  Command/MigrationsDiffDoctrineCommand.php
  Command/MigrationsDumpSchemaDoctrineCommand.php
  Command/MigrationsExecuteDoctrineCommand.php
  Command/MigrationsGenerateDoctrineCommand.php
  Command/MigrationsLatestDoctrineCommand.php
  Command/MigrationsMigrateDoctrineCommand.php
  Command/MigrationsRollupDoctrineCommand.php
  Command/MigrationsStatusDoctrineCommand.php
  Command/MigrationsUpToDateDoctrineCommand.php
  Command/MigrationsVersionDoctrineCommand.php
  composer.json
  composer.lock
Labels: Enhancement

#285 Fix type conversion of CLI options
  Command/Helper/DoctrineCommandHelper.php
  phpstan.neon
Labels: Bug

#288 Fix type conversion of CLI options
  Command/Helper/DoctrineCommandHelper.php
  phpstan.neon
Labels: Bug
