Repository doctrine/DoctrineMigrationsBundle, pull requests merged in 2021-11, with the labels that each got.

#450 Reuse workflows from upstream
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
  DependencyInjection/DoctrineMigrationsExtension.php
  composer.json
  phpstan.neon
  psalm-baseline.xml
  psalm.xml
Labels: Improvement

#455 Update branch metadata
  .doctrine-project.json
  .symfony.bundle.yaml
Labels: Documentation

#456 Reuse Symfony unstable workflow
  .github/workflows/continuous-integration.yml
  composer.json
Labels: Improvement

#458 fix toolbar and menu not showing in profiler
  Resources/views/Collector/migrations.html.twig
Labels: Bug
