Repository doctrine/DoctrineMigrationsBundle, pull requests merged in 2023-11, with the labels that each got.

#512 Doctrine CS 12
  DependencyInjection/CompilerPass/ConfigureDependencyFactoryPass.php
  Tests/DependencyInjection/DoctrineCommandsTest.php
  composer.json
Labels: Improvement

#515 Test on PHP 8.2 and 8.3
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  phpstan.neon.dist
  psalm.xml
Labels: CI

#439 Remove unnecessary empty line
  Resources/doc/index.rst
Labels: Documentation

#513 Drop support for Symfony 3 and 4
  DependencyInjection/Configuration.php
  Tests/DependencyInjection/DoctrineMigrationsExtensionTest.php
  composer.json
  phpstan.neon.dist
Labels: Improvement

#517 Psalm 5
  DependencyInjection/Configuration.php
  composer.json
  psalm-baseline.xml
  psalm.xml
Labels: Static Analysis

#516 Test against dev deps in CI
  .github/workflows/continuous-integration.yml
  Tests/DependencyInjection/DoctrineCommandsTest.php
  Tests/DependencyInjection/DoctrineMigrationsExtensionTest.php
  Tests/Fixtures/Migrations/ContainerAwareMigration.php
  Tests/Fixtures/Migrations/Migration001.php
  composer.json
Labels: CI

#518 Deprecate ContainerAwareMigrationFactory
  DependencyInjection/DoctrineMigrationsExtension.php
  MigrationsFactory/ContainerAwareMigrationFactory.php
  Tests/DependencyInjection/DoctrineMigrationsExtensionTest.php
  composer.json
  phpunit.xml.dist
  psalm.xml
Labels: Deprecation

#519 Prepare 3.3.0
  .doctrine-project.json
  .symfony.bundle.yaml
Labels: Documentation
