Repository doctrine/DoctrineMigrationsBundle, pull requests merged in 2025-01, with the labels that each got.

#568 Run tests with PHP 8.4
  .github/workflows/continuous-integration.yml
Labels: CI

#565 PHPStan 2
  composer.json
Labels: Static Analysis

#572 Add grammar constraint for phpcs.xml.dist
  phpcs.xml.dist
Labels: Enhancement

#551 Update index.rst: Minor improvements at "Manual Tables"
  Resources/doc/index.rst
Labels: Documentation

#575 Upgrade to PHPUnit 11
  composer.json
  phpunit.xml.dist
  tests/DependencyInjection/DoctrineCommandsTest.php
  tests/DependencyInjection/DoctrineMigrationsExtensionTest.php
Labels: Test Suite

#576 Remove support for Symfony 5
  composer.json
  tests/DependencyInjection/DoctrineMigrationsExtensionTest.php
Labels: Improvement

#578 Drop useless phpcs configuration
  phpcs.xml.dist
Labels: Enhancement

#579 Normalize composer.json
  .github/workflows/composer-lint.yml
  composer.json
Labels: CI

#526 Add support for --complete
  config/services.xml
  src/DependencyInjection/DoctrineMigrationsExtension.php
  src/EventListener/SchemaFilterListener.php
  tests/Collector/EventListener/SchemaFilterListenerTest.php
Labels: Improvement
